version: '3.7'

services:
  db:
    image: postgres:15.1
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.20
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '9000:80'

volumes:
  postgres-data:
  pgadmin:
